# Generated by Django 2.2 on 2019-06-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190610_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='size',
        ),
    ]
